### ISSUE TITLE
Issue when model.matrix drops columns

### ISSUE THREAD

**Issue by covaruber** [Biometris/LMMsolver#1]
Dear Bart, I hope you're doing well. Thanks for making this package available, is great! I found a bug while preparing a short training for some scientists that I thought you may be interested in fixing. I hope is not that I just did something wrong haha.

There seems to be an issue when you specify a model and somehow some columns are dropped when building the incidence matrix. The model runs well but seems to be some lines of code at the end when you try to assign the names to the coefficients that returns an error because the number of coefficients and number of names to be assigned don't match. Here I attach an rds file and the code to replicate the issue.

```
# devtools::install_github("Biometris/LMMsolver")
library(LMMsolver)
dt <- read.csv("DT_recurrent_selection.csv")
dt$idF <- as.factor(paste0("id",dt$id))
dt$genF <- as.factor(paste0("gen",dt$gen))
dt$envF <- as.factor(paste0("env",dt$env))

head(dt)
m3 <- LMMsolve(pheno~ genF + idF,
           data=dt)

# there's colinearity so 9 columns are dropped 
m4 <- lm(pheno~ genF + idF,
         data=dt)
length(which(is.na(m4$coefficients)))
length(m4$coefficients)

X <- model.matrix(~genF + idF, data=dt)
dim(X)       
colnames(X)
```

Let me know if you can replicate the issue. I hope this is useful. Take care.

Cheers,
Eduardo

[DT_recurrent_selection.csv](https://github.com/Biometris/LMMsolver/files/10467773/DT_recurrent_selection.csv)

**Comment by covaruber** [comment]
My bad Bart, I just noticed that genF only has one level and this seems to be causing the issue. Sorry for that. You may still want to check why it breaks but I guess now is less likely to happen I assume. 

Cheers,

**Comment by BartJanvanRossum** [comment]
Dear Eduardo, 
Thanks for submitting the issue and the clear code to reproduce it. Even though it is less likely to occur since it only happens when a variable only has one factor level, I still think it is a bug. So I'm going to reopen the issue.
Cheers,
Bart-Jan

**Comment by BartJanvanRossum** [comment]
This should be fixed now in the develop branch of the package. It turned out to be a bug after all. genF did have 10 levels, so there was no problem there. The problem was in the assignment of the names to the coefficients as you already suggested in your first post.

**Comment by covaruber** [comment]
Great to hear Bart-Jan and thanks for the quick fix, works well now. I'll let you know if I find something else :) have a great day.
