### ISSUE TITLE
Adding a predict function

### ISSUE THREAD

**Issue by covaruber** [Biometris/LMMsolver#2]
Dear Bart and Martin, I hope you're doing well. Hey, I was wondering if you're planning to add a predict function for the LMMsolve objects? I noticed that you already have the method for calculating standard errors for the matrix D of linear combinations but I couldn't find a predict function.

I think you could have a simple implementation if you allow for the output of the LMMsolve function to return the W = [X Z] matrix and if possible the final dataset used in the model fitting. Then the predict function could be something like this:

```
library(LMMsolver)
library(Matrix)
data(john.alpha, package = "agridat")
model <- LMMsolve(fixed = yield ~ 1 ,
                      random = ~gen + rep,
                      data = john.alpha)
# 3 arguments needed
object=model # 1) model object
# this implementation would need the model object to include the W=[X Z] matrix and the data
object$data <- john.alpha
X <- sparse.model.matrix(~1, data=john.alpha)
Z1 <- sparse.model.matrix(~gen-1, data=john.alpha)
Z2 <- sparse.model.matrix(~rep-1, data=john.alpha)
object$W <- cbind(X,Z1,Z2)
#
D="gen" # classify argument
Dtable=NULL # optional table to specify what should be included, averaged or both
pp = predict.LMMsolve(object=object, D=D, Dtable=Dtable)
head(pp$pvals)

"predict.LMMsolve" <- function(object, Dtable=NULL, D, ...){
  classify <- D # save a copy before D is overwriten
  # complete the Dtable withnumber of effects in each term
  effectsN <- object$EDdf$Model
  start = end = numeric(); add <- 1
  for(i in 1:length(effectsN)){
    start[i] = add
    end[i] = start[i] + effectsN[i] - 1
    add = end[i] + 1
  }
  # fill the Dt table
  if(is.null(Dtable)){ # if user didn't provide the Dtable
    Dtable <- object$EDdf; Dtable <- Dtable[-nrow(Dtable),] # remove residual
    Dtable$include <- FALSE; Dtable$average <- FALSE # we extract it from the model
    if(is.character(D)){ # if D is properly provided
      pickTerm <- which(Dtable[,"Term"]==D) # the default rule is to invoke D in the Dtable
      if(length(pickTerm) > 0){Dtable[pickTerm,"include"]=TRUE; Dtable[pickTerm,"average"]=TRUE }else{Dtable[,"include"]=TRUE}# otherwise if the desired term is not present we just provide fitted values
    }
  }
  # user has provided D as a classify
  if(is.character(D)){
    # create model matrices to form D
    P <- sparse.model.matrix(as.formula(paste0("~",D,"-1")), data=object$data)
    tP <- t(P)
    W <- object$W
    D = tP %*% W
    # apply rules in Dtable
    for(iRow in 1:nrow(Dtable)){
      w <- start[iRow]:end[iRow]
      # include/exclude rule
      if(Dtable[iRow,"include"]){ # set to 1
        subD <- D[,w]
        subD[which(subD > 0, arr.ind = TRUE)] = 1
        D[,w] <- subD
        # average rule
        if(Dtable[iRow,"average"]){ # set to 1
          # average the include set
          subD <- apply(subD,1,function(x){
            v <- which(x > 0);  x[v] <- x[v]/length(v)
            return(x)
          })
          D[,w] <- subD
        }
      }else{ # set to zero
        if(Dtable[iRow,"average"]){ # set to 1
          subD <- D[,w] + 1
          subD <- subD/subD
          subD[which(subD > 0, arr.ind = TRUE)] = subD[which(subD > 0, arr.ind = TRUE)]/ncol(subD)
          D[,w] <- subD
        }else{
          D[,w] <- D[,w] * 0
        }
      }
    }
    interceptColumn <- grep("Intercept",colnames(D) )
    if(length(interceptColumn) > 0){D[,interceptColumn] = 1}
  }else{ }# user has provided D as a matrix to do direct multiplication
  
  bu <- unlist(object$coefficients)
  predicted.value <- D %*% bu
  vcov <- D %*% solve(object$C) %*% t(D) # you already have a more efficient function , just using this for the sake of example
  std.error <- sqrt(diag(vcov))
  pvals <- data.frame(id=colnames(P),predicted.value=predicted.value[,1], std.error=std.error)
  if(is.character(classify)){colnames(pvals)[1] <- classify}
  return(list(pvals=pvals,D=D,vcov=vcov, Dtable=Dtable))
} 

```

Maybe you already have a better implementation but this may work as a starting point to make something more sophisticated.

Cheers,
Eduardo

**Comment by martinboer** [comment]
Hi Eduardo, Thanks for your message! The `predict` function is one of the first things we would like to add to LMMsolver. For fitting (tensor) P-splines we already have the `obtainSmoothTrend` function, this needs to be further extended to the more general case with fixed and random effects for the `predict` function. 

Thanks for your example code!

Cheers, Martin

**Comment by covaruber** [comment]
That's great news Martin. If you add the W =[X Z] matrix and the data used to the output I will be happy to contribute. I didn't add the regular rules that asreml uses for what should be included or averaged because I didn't want to make the function larger but is easy to recreate the asreml output if the right terms are included or averaged. Great job with this package, I am quite impressed and looking forward to contribute.  

Cheers,
Eduardo

**Comment by covaruber** [comment]
Dear Bart and Martin, I was wondering if there's any way to allow the return of the X and Z matrices built to be returned in the output if needed by the user. This way I could develop a small function for an analytical pipeline where we're using LMMsolve and we need predictions. I know you probably don't want to make the output object heavy unnecessarily but my team would greatly appreciate it. 

Cheers,
Eduardo

**Comment by martinboer** [comment]
Thanks Eduardo, good idea. We will add the X and Z matrices as (optional) output. Cheers, Martin

**Comment by martinboer** [comment]
Hi Eduardo,

I added output of X and Z design matrices (plus response variable and vcov / precision matrices).

Cheers, Martin

**Comment by covaruber** [comment]
Thanks a lot Martin, this is greatly appreciated. This saves our life. Once again, congratulations on this package and thanks, is a big step forward.

Cheers,
Eduardo
