### ISSUE TITLE
Two-stage analysis in LMMsolver

### ISSUE THREAD

**Issue by covaruber** [Biometris/LMMsolver#3]
Dear Martin and Bart,

I hope you're doing well. Hey, I was wondering if you have an example on how to fit the second stage from the two-stage approach using LMMsolver. I tried using the 'family' argument with 

```
fixed=trait~env
random=~geno + gene:env
family=quasi(link = "identity", variance = "constant")
weights= w # w is 1/(se^2) from the first stage
```

to force the error variance to be equal to 1. Since we have some pipelines depending on LMMsolver I want to make sure I am not fitting the wrong arguments in the model. Thanks in advance and you two have a great weekend.

Cheers,
Eduardo

**Comment by martinboer** [comment]
Hi Eduardo. 

Thanks for your message. We don't have an example yet for two-stage approach, but we will try to implement (and first check the results with other software).

Cheers,
Martin

**Comment by covaruber** [comment]
OK thanks Martin. I have been testing it with multiple examples and this seems to do the job for getting the right variance components and BLUPs but I just wanted to make sure. I leave one example but I've been running several and seems to be consistent. I like your implementation because is faster. Have a great day!


```
library(sommer)
data(DT_h2)
DT <- DT_h2
head(DT)
envs <- unique(DT$Env)

# stage 1
BLUEL <- list()
XtXL <- list()
for(i in 1:length(envs)){
  ans1 <- mmer(y~Name-1,
               random=~Block,
               verbose=FALSE,
               data=droplevels(DT[which(DT$Env == envs[i]),]
               )
  )
  ans1$Beta$Env <- envs[i]
  
  BLUEL[[i]] <- ans1$Beta
  XtXL[[i]] <- 1/ diag(ans1$VarBeta) # alternatively could be the entire matrix
}

DT2 <- do.call(rbind, BLUEL)
OM <- diag(unlist(XtXL)) # alternatively do.call(adiag1,XtXL)  for a fully efficient two-stage
DT2$w <- unlist(XtXL)

## stage 2

library(asreml)
ans1 <- asreml::asreml(Estimate~Env,
               random=~Effect + Env:Effect, 
               family=asreml::asr_gaussian(dispersion = 1),
               weights= w ,# w is 1/(se^2) from the first stage
               data=DT2)
summary(ans1)$varcomp

m <- matrix(1/var(DT2$Estimate, na.rm = TRUE))
ans2 <- mmec(Estimate~Env,
             random=~Effect + Env:Effect, 
             rcov=~vsc(isc(units,thetaC = matrix(3), theta = m)),
             W=OM, # could be the entire omega matrix
             verbose=TRUE,
             data=DT2
)
summary(ans2)$varcomp 



ans3 <- LMMsolver::LMMsolve(Estimate~Env,
                    random=~Effect + Env:Effect, 
                    family=quasi(link = "identity", variance = "constant"),
                    weights= "w" ,# w is 1/(se^2) from the first stage
                    data=DT2)
ans3$VarDf # same variance components

## all give the same variance components and same blips

plot(ans1$coefficients$random, ans2$u) # asreml and sommer

plot(ans1$coefficients$random, c(ans3$coefficients$Effect, ans3$coefficients$`Effect:Env`)) # asreml and LMMsolver
```

Cheers,
Eduardo

**Comment by martinboer** [comment]
Thanks Eduardo! 

I also checked another example, and the `family=quasi(link = "identity", variance = "constant")` for `LMMsolver` gives same result as sommer and asreml.  

Cheers, Martin
