### ISSUE TITLE
pvalue calcuation from deviance

### ISSUE THREAD

**Issue by yan-cheng-lin** [Biometris/LMMsolver#5]
Hello,

Thank you for making such powerful tool.
I have a question regarding to the pvalue calcuation from deviance when testing null and alternative model.
In the last two chunks of [vignettes/Solving_Linear_Mixed_Models.Rmd](https://github.com/Biometris/LMMsolver/blob/HEAD/vignettes/Solving_Linear_Mixed_Models.Rmd):

Deviance difference between null and alternative model.
dev <- dev4 - dev5
Calculate approximate p-value. 
minlog10p <- -log10(**0.5** * pchisq(dev, 1, lower.tail = FALSE))
round(minlog10p, 2)

I was wandering why you have to multiply 0.5 to your p-value? 
I also calculate pvalue of likelihood ratio test by ASReml (REMLRT), it will be the same if I did not multiply 0.5.

P.S. It seems that in R/statgenMPP, same formula as LMMsolver was also used.
Thank you.

Best regards,
Yan-Cheng

**Comment by martinboer** [comment]
Hi Yan-Cheng,

Thanks for your interest in our R-package! The factor 0.5 is based on a paper by Self and Liang 1987 ( https://www.tandfonline.com/doi/abs/10.1080/01621459.1987.10478472), and is often used as good approximation of the p-value for variance components. Variance components are zero or positive, that is in short the reason of the factor half.

In statgenMPP we use the same approach indeed, see https://doi.org/10.1093/bioinformatics/btac662 for brief explanation

Best Regards,
Martin

**Comment by yan-cheng-lin** [comment]
Hi Martin,

I got it, thank you for your rapid response.

Best regards,
Yan-Cheng

**Comment by martinboer** [comment]
Ok!

Martin
